# Generated by Django 5.2.3 on 2025-08-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_profile_profile_picture_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
