# Generated by Django 5.2.3 on 2025-08-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
