# Generated by Django 5.2.3 on 2025-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_options_item_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
    ]
