# Generated by Django 5.2.3 on 2025-08-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INFO', 'Info'), ('OFFER', 'Offer'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('SOLD', 'Sold')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
